In [1]:
import pandas as pd
import numpy as np
import csv
from scipy.linalg import fractional_matrix_power
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import CCA
from sklearn.cluster import KMeans
from sklearn.cluster import SpectralClustering
from sklearn.manifold import SpectralEmbedding
from sklearn.ensemble import RandomForestClassifier
import sklearn.metrics.pairwise as kernel

In [2]:
N = 10000
n = 6000
# feature 10000*1084
feature = np.genfromtxt('Extracted_features.csv',delimiter = ',',dtype = 'float')
# seed 60*2
seed = np.genfromtxt('Seed.csv',delimiter = ',',dtype = 'int')
# # adjacency matrix A
# A = np.zeros((n,n))
# with open('Graph.csv','rb') as csvfile:
#     reader = csv.reader(csvfile, delimiter=',')
#     for row in reader:
#         A[int(row[0])-1,int(row[1])-1] = 1
#         A[int(row[1])-1,int(row[0])-1] = 1

In [10]:
A = kernel.rbf_kernel(feature,feature,gamma=0.0078)
for nc in range(40,110,10):
    X = SpectralEmbedding(n_components=nc,affinity='precomputed').fit_transform(A)
    # initialize kmeans with mean of seeds
    ip = np.vstack(np.mean(X[seed[seed[:,1] == i,0] - 1,:], axis = 0) for i in range(10))
    # kmeans
    kmeans = KMeans(n_clusters = 10, init = ip, random_state = 0).fit(X)
    # kmeans result of seeds
    r1 = np.hstack((seed, np.reshape(kmeans.labels_[seed[:,0] - 1],(len(seed),1))))
    print nc, sum(r1[:,1] == r1[:,2])/(1.0*len(r1))
    confm = np.zeros((10,10))
    for i in range(len(r1)):
        confm[r1[i,1],r1[i,2]] += 1
    print confm

C:\Users\dancyfang\Anaconda2\lib\site-packages\sklearn\cluster\k_means_.py:889: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


40 0.6
50 0.533333333333
60 0.583333333333
70 0.6
80 0.616666666667
90 0.583333333333
100 0.6


In [3]:
for nc in range(100,200,10):
    X = SpectralEmbedding(n_components=nc,affinity='rbf').fit_transform(feature)
    # initialize kmeans with mean of seeds
    ip = np.vstack(np.mean(X[seed[seed[:,1] == i,0] - 1,:], axis = 0) for i in range(10))
    # kmeans
    kmeans = KMeans(n_clusters = 10, init = ip, random_state = 0).fit(X)
    # kmeans result of seeds
    r1 = np.hstack((seed, np.reshape(kmeans.labels_[seed[:,0] - 1],(len(seed),1))))
    print nc, sum(r1[:,1] == r1[:,2])/(1.0*len(r1))
    confm = np.zeros((10,10))
    for i in range(len(r1)):
        confm[r1[i,1],r1[i,2]] += 1
    print confm

C:\Users\dancyfang\Anaconda2\lib\site-packages\sklearn\cluster\k_means_.py:889: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


100 0.6
[[ 3.  0.  0.  0.  0.  3.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  1.  1.  3.  0.  0.  0.  1.]
 [ 1.  1.  0.  0.  0.  1.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  0.  0.  2.  0.  1.]
 [ 0.  0.  0.  2.  0.  2.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  0.  1.  0.  3.]]
110 0.6
[[ 3.  0.  0.  0.  0.  3.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  4.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  4.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  1.  2.  2.  0.  0.  0.  1.]
 [ 1.  1.  0.  0.  0.  1.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.  3.  0.  1.]
 [ 0.  0.  0.  2.  0.  1.  0.  0.  2.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  1.  3.]]
120 0.65
[[ 4.  0.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  

In [37]:
for nc in range(30,100,10):
    X = SpectralEmbedding(n_components=nc,affinity='nearest_neighbors').fit_transform(feature)
    # initialize kmeans with mean of seeds
    ip = np.vstack(np.mean(X[seed[seed[:,1] == i,0] - 1,:], axis = 0) for i in range(10))
    # kmeans
    kmeans = KMeans(n_clusters = 10, init = ip, random_state = 0).fit(X)
    # kmeans result of seeds
    r1 = np.hstack((seed, np.reshape(kmeans.labels_[seed[:,0] - 1],(len(seed),1))))
    print nc, sum(r1[:,1] == r1[:,2])/(1.0*len(r1))
    confm = np.zeros((10,10))
    for i in range(len(r1)):
        confm[r1[i,1],r1[i,2]] += 1
    print confm

30 0.6
[[ 3.  0.  0.  0.  0.  3.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  5.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  4.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  1.  0.  2.  0.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  1.  2.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  4.  2.  0.]
 [ 0.  0.  0.  3.  0.  1.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  2.  3.]]
40 0.666666666667
[[ 5.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  5.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  1.  0.  0.  0.  2.]
 [ 0.  0.  0.  1.  1.  4.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  2.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  4.  0.  0.]
 [ 0.  0.  0.  1.  0.  4.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  2.  0.  0.  0.  3.]]
50 0.65
[[ 5.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  

KeyboardInterrupt: 

In [35]:
confm = np.zeros((10,10))
for i in range(len(r1)):
    confm[r1[i,1],r1[i,2]] += 1
confm

array([[ 5.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  1.,  1.,  4.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  2.,  3.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  4.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  2.,  0.,  0.,  0.,  3.]])

In [6]:
result = kmeans.labels_[n:]
sum(result[])

(4000L,)

In [7]:
# save to txt
r = np.hstack((np.reshape([i+n+1 for i in range(N-n)],(N-n,1)), np.reshape(result,(N-n,1))))
np.savetxt('result3.csv', r, delimiter = ',', fmt = '%d', header = "Id,Label", comments = '')